package com.appdirect.subscription.enums;

public enum Type {
	NEW, MIGRATION, ADOPTION, METERED_USAGE, FREE_TRIAL_ACTIVATION, BUNDLED, TERMINATION_FEE, END_OF_CONTRACT_MIGRATION, REFUND, CREDIT, ONE_TIME_FEE, ADDITIONAL_FEE;
}
